Update rogue

diff --git a/rogue b/rogue
--- a/rogue
+++ b/rogue
@@ -123,71 +123,81 @@ run_this_context=false
 [ ! -f is_docker ] && run_this_context=true
 
 path="$script_dir"
-echo "$script_dir and $path_array"
+full_path="$script_dir/$inpath"
+parent_path=$(dirname "$full_path")
+if [[ -d full_path ]] || [[ ! -x full_path ]] then;
+    header "Error must provide an executable file"
+    exit 1
+elif [[ -d parent_path ]]; then
+    # find a yaml file and run the docker 
+else
+    header Unknown error occured
+fi
+
+echo "$script_dir/$inpath"
 while IFS= read -r path_e; do
-	path="$path/$path_e"
-	echo "doin path $path"
-	exit 
-	#check if path is a directory or file
-	if [[ -d $path ]]; then
-		#iterate all files in path that are hidden files and source them
-		for file in $path/.*; do
-			if [[ -f $file ]]; then 
-				#if file ends with .sh or .env
-				if [[ $file == *.sh || $file == *.env ]]; then
-					source $file
-				else
-					env $file
-				fi
-			fi
-		done
-		continue
-	fi
-	
-	
-	if [[ -f $path ]]; then #if path variable is a file then exec it
-		if [[ $file == *.yaml ]] && [[ "$run_this_context" = false ]]; then
-		#Run image
-		#d_compose_args=(-f <( envsubst < docker-compose.yaml ) --env-file <( env ))
-		# up ${d_compose[@]} -f <( envsubst < docker-compose.yaml ) --env-file <( env ) up --pull always --build
-		#run
-		${d_compose[@]} -f <( envsubst < docker-compose.yaml ) --env-file <( env ) pull
-		#get workdir from image
-		#WORKDIR=$(docker image inspect -f '{{.Config.WorkingDir}}' "${image}")
-		${d_compose[@]} -f <( envsubst < docker-compose.yaml ) --env-file <( env ) run --build roguesecrets /home/roguesecrets/main.sh
-		if ! [ -z "$is_service" ]; then
-		${d_compose[@]} -f <( envsubst < docker-compose.yaml ) down
-		fi
-		
-		#export secrets into environment
-		rogue_envvars="/tmp/RogueCLI/.env"
-		if [ -f $rogue_envvars ]; then
-		header "Exporting secrets"
-		echo "$rogue_envvars"
-		case "$(uname)" in
-		LINUX) export $(grep -v '^#' $rogue_envvars | xargs -d '\n') ;;
-		FreeBSD|Darwin) export $(grep -v '^#' $rogue_envvars | xargs -0) ;;
-		*) echo "Error exporting values" ;;
-		esac
-		rm $rogue_envvars
-		fi
-		break
-		else
-   	exec env $path "${@:2}" < /dev/tty
-  		# if test ! -t 0; then
-  		#     #echo "Read from stdin"
-  		#     #currently doesnt work with decrypt
-  		#     exec env $path "${@:2}" < /dev/stdin # or < /proc/$$/fd/0 for stdin
-  		# else
-  		# 	exec env $path "${@:2}" < /dev/tty # or < /proc/$$/fd/0 for stdin
-  		# fi
-  		#if it fails then exit with the same error number as the previous command
-  		if [ $? -ne 0 ]; then
-  			exit $?
-  		fi
-  		break
-  fi
-	fi
-done <<< "$path_array"
+    path="$path/$path_e"
+
+    #check if path is a directory or file
+    if [[ -d $path ]]; then
+        #iterate all files in path that are hidden files and source them
+        for file in $path/.*; do
+            if [[ -f $file ]]; then
+                #if file ends with .sh or .env
+                if [[ $file == *.sh || $file == *.env ]]; then
+                    source $file
+                else
+                    env $file
+                fi
+            fi
+        done
+        continue
+    fi
+
+    if [[ -f $path ]]; then #if path variable is a file then exec it
+        if [[ $file == *.yaml ]] && [[ "$run_this_context" = false ]]; then
+            #Run image
+            #d_compose_args=(-f <( envsubst < docker-compose.yaml ) --env-file <( env ))
+            # up ${d_compose[@]} -f <( envsubst < docker-compose.yaml ) --env-file <( env ) up --pull always --build
+            #run
+            ${d_compose[@]} -f <(envsubst <docker-compose.yaml) --env-file <(env) pull
+            #get workdir from image
+            #WORKDIR=$(docker image inspect -f '{{.Config.WorkingDir}}' "${image}")
+            ${d_compose[@]} -f <(envsubst <docker-compose.yaml) --env-file <(env) run --build roguesecrets /home/roguesecrets/main.sh
+            if ! [ -z "$is_service" ]; then
+                ${d_compose[@]} -f <(envsubst <docker-compose.yaml) down
+            fi
+
+            #export secrets into environment
+            rogue_envvars="/tmp/RogueCLI/.env"
+            if [ -f $rogue_envvars ]; then
+                header "Exporting secrets"
+                echo "$rogue_envvars"
+                case "$(uname)" in
+                LINUX) export $(grep -v '^#' $rogue_envvars | xargs -d 'n') ;;
+                FreeBSD | Darwin) export $(grep -v '^#' $rogue_envvars | xargs -0) ;;
+                *) echo "Error exporting values" ;;
+                esac
+                rm $rogue_envvars
+            fi
+            break
+        else
+            exec env $path "${@:2}" </dev/tty
+            # if test ! -t 0; then
+            #     #echo "Read from stdin"
+            #     #currently doesnt work with decrypt
+            #     exec env $path "${@:2}" < /dev/stdin # or < /proc/$$/fd/0 for stdin
+            # else
+            # 	exec env $path "${@:2}" < /dev/tty # or < /proc/$$/fd/0 for stdin
+            # fi
+            #if it fails then exit with the same error number as the previous command
+            if [ $? -ne 0 ]; then
+                exit $?
+            fi
+            break
+        fi
+    fi
+done <<<"$path_array"
+
 
 
